### ISSUE TITLE
Allowing more than one type of separator

### ISSUE THREAD

**Issue by mervyn-wee** [Tkko/Flutter_Pinput#142]
**Is your feature request related to a problem? Please describe.**
Right now, the `separator` and `separatorPositions` fields only allow one type of separator.

**Describe the solution you'd like**
I would like to be able to apply more than one type of separator, perhaps `SizedBox(width: 8)` for position 1, `SizedBox(width: 12)` for position 2, and so on. 

I'm thinking that `final Widget? separator` and `List<int>? separatorPositions separatorPositions` can be refactored into a callback function `Widget Function(int index)? separatorBuilder`. This will allow the flexibility of allowing more than one separator to be inserted. 

**Describe alternatives you've considered**
NA

**Additional context**
~~I'd be happy to put up a PR.~~ 
edit: I've put up a PR over [here](https://github.com/Tkko/Flutter_Pinput/pull/143)

**Comment by Tkko** [comment]
Thanks again for the PR, just published the version 2.4.0 with your changes in it.

**Comment by proof-of-c** [comment]
@Tkko Hi! this release broke production pipelines of some of my apps yesterday.

We were using the `separator` param but suddenly it didn't exist anymore, we investigated and saw that your package did remove this param by incrementing the MINOR version.

---

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> - **MAJOR** version **when you make incompatible API changes**
> - MINOR version when you add functionality in a backward compatible manner
> - PATCH version when you make backward compatible bug fixes
> - Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

https://semver.org/

---

That said, I think there is no solution because it's already published, so I'm just providing feedback.
