### ISSUE TITLE
this error is showing after update 2.2.31 version update

### ISSUE THREAD

**Issue by alokesh-git** [Tkko/Flutter_Pinput#147]
\GeneratedPluginRegistrant.java:129: error: cannot find symbol
      flutterEngine.getPlugins().add(new fman.ge.smart_auth.SmartAuthPlugin());
                                                           ^
  symbol:   class SmartAuthPlugin
  location: package fman.ge.smart_auth
1 error

**Comment by Tkko** [comment]
SmartAuth was removed from Pinput in versions ^5.0.0, so that I don't force people who don't want to use SMS autofill to depend on it and avoid building issue like this.

If you need the SMS autofill on android and still having same issue, please checkout the [SmartAuth](https://github.com/Tkko/flutter_smart_auth) repo.
