### ISSUE TITLE
[Q] Autofill and App signature - When using my own backend server

### ISSUE THREAD

**Issue by burekas7** [Tkko/Flutter_Pinput#170]
Hi,

I need some clarification about using the AutoFill process and the app signature.

When I use the "smsRetrieverApi" method.

1) Who is actually responsible for sending the SMS message? My backend server, right?
2) If my server generates the content of the SMS message, how does it know what the app signature is? (hash)
How do I get this value and transfer to the server?
Does Pinput has a method to get it like `getAppSignature`? 
Or should I use SmartAuth for that? 
Do I have a way to get the SmartAuth instance?
3) Who is actually responsible for verifying the received pin code? My backend server, right?
4) Does the app listen to SMS messages forever or only on the screen where the pinput is? Do I have control over it?
5) Just to make sure I understand it correctly, for iOS it will also fill the code automatically like in Android, or it will only show the code in the keyboard so it will fill it by pressing on it manually?

Thanks.

**Comment by matias-casco** [comment]
Hi @burekas7 

2. I generate the SMS from my server and I used SmartAuth to get the App Signature, it worked well on debug mode so far. I did not find any getAppSignature method on pinput package, I just found it on smart_auth package that is a dependecy of pinput package.

**Comment by Tkko** [comment]
1. Yes
2. https://stackoverflow.com/questions/53849023/android-sms-retriever-api-computing-apps-hash-string-problem
3. When user gets the code and it will be autofilled in the Pinput, you should send the request to the backend containing phone number and the OTP code and the backend should return if the OTP is correct.
4. When Pinput is removed from the widget tree it won't listed for incoming SMSes
5. Yes


Additionally, [SmartAuth](https://github.com/Tkko/flutter_smart_auth) was removed from Pinput in versions ^5.0.0, so that I don't force people who don't want to use SMS autofill to depend on it and avoid building issue.
